# 构建数据集

切分传入张量的第一维度，生成输入特征/标签对，构建数据集   
data = tf.data.Dataset.from_tensor_slices((输入特征, 标签))

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
features = tf.constant([23,12,3,7,18])
labels = tf.constant([0,1,1,1,0])

In [6]:
dataset = tf.data.Dataset.from_tensor_slices((features,labels))
print(dataset)

<TensorSliceDataset shapes: ((), ()), types: (tf.int32, tf.int32)>


In [7]:
for item in dataset:
    print(item)

(<tf.Tensor: shape=(), dtype=int32, numpy=23>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=7>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=18>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
