# 特殊张量

In [2]:
import tensorflow as tf
import numpy as np

#### <font color='red'>全 0 张量</font>

> 创建全为0的张量   
tf. zeros(维度) 

In [5]:
a = tf.zeros([2,2])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

#### <font color='red'>全 1 张量</font>

> 创建全为1的张量   
tf. ones(维度) 

In [6]:
b = tf.ones([2,2])
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

#### <font color='red'>指定值张量</font>

> 创建全为指定值的张量    
tf. fill(维度，指定值)

In [7]:
c = tf.fill([2,2],9)
c   

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]])>