# 独热编码

独热编码（one-hot encoding）：在分类问题中，常用独热码做标签，   
标记类别：1表示是，0表示非。

       (0狗尾草鸢尾 1杂色鸢尾 2弗吉尼亚鸢尾 ）  
标 签： 1    
独热码: (0.        1.         0.)  

tf.one_hot()函数将待转换数据，转换为one-hot形式的数据输出。   
tf.one_hot (待转换数据, depth=几分类)

In [2]:
import tensorflow as tf
import numpy as np

In [4]:
classes = 3
# 输入的元素值最小为0，最大为2
labels = tf.constant([1,0,2])
print(labels)
output = tf.one_hot(labels, depth = classes)
print(output)

tf.Tensor([1 0 2], shape=(3,), dtype=int32)
tf.Tensor(
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
