# 常用函数-矩阵相乘

实现两个矩阵的相乘   
tf.matmul(矩阵1，矩阵2)

<font color='red'>两个矩阵相乘，第一个数的列数必须与第二个数的行数相等</font>

In [1]:
import tensorflow as tf
import numpy as np

In [9]:
a = tf.fill([3,2], 3.)
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.],
       [3., 3.]], dtype=float32)>

In [10]:
b = tf.ones([2,3])
b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
c = tf.matmul(a,b)
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>