# 常用函数-指定维度最大值

返回张量沿指定维度最大值的索引   
tf.argmax (张量名,axis=操作轴)

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
a = np.array([[2,3,1,5],[18,11,20,13],[22,23,24,10],[1,10,22,16],[17,14,21,20]])
a

array([[ 2,  3,  1,  5],
       [18, 11, 20, 13],
       [22, 23, 24, 10],
       [ 1, 10, 22, 16],
       [17, 14, 21, 20]])

In [4]:
# 返回每一列（经度）最大值的索引
b = tf.argmax(a, axis=0)
b

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 2, 2, 4], dtype=int64)>

In [5]:
# 返回每一行（纬度）最大值的索引
c = tf.argmax(a, axis=1)
c

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 2, 2, 2, 2], dtype=int64)>

<font color='red'>[注意]返回的是下标index</font>