# 张量

In [1]:
import tensorflow as tf

In [5]:
a = tf.constant([1,5], dtype=tf.int64)
print(a)

tf.Tensor([1 5], shape=(2,), dtype=int64)


In [7]:
print(a.dtype)

<dtype: 'int64'>


In [8]:
print(a.shape)

(2,)


In [9]:
b = tf.constant(5)
print(b)

tf.Tensor(5, shape=(), dtype=int32)


In [10]:
c = tf.constant([1,2])
print(c)

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [12]:
d = tf.constant([[1,2],[3,4]])
print(d)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [13]:
e = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(e)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


#### <font color='red'>shape表示形状是标量，还是一维、二维、三维。。。数据</font>
#### <font color='red'>dtype表示数据类型是int64,还是int32</font>