# 平均-求和

计算张量沿着指定维度的平均值  
tf.reduce_mean (张量名，axis=操作轴)  

计算张量沿着指定维度的和  
tf.reduce_sum (张量名，axis=操作轴)  

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [4]:
b = tf.convert_to_tensor(a, dtype=tf.int32)
b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [6]:
c = tf.constant([[1,2,3],[2,2,4]])
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 2, 4]])>

In [8]:
# 跨行
d = tf.reduce_mean(c, axis=0)
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [9]:
# 跨列
e = tf.reduce_mean(c, axis=1)
e

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2])>

In [10]:
# 跨行
f = tf.reduce_sum(c, axis=0)
f

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 7])>

In [11]:
# 跨列
h = tf.reduce_sum(c, axis=1)
h

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 8])>