# 构建网格-拉直-配对

+ np.mgrid[ ] 返回间隔数值点，可同时返回多组， [起始值 结束值)
+ np.mgrid[ 起始值 : 结束值 : 步长 ，起始值 : 结束值 : 步长 , … ] 
                                
+ x.ravel( ) 将x变为一维数组，“把 . 前变量拉直”
                                
+ np.c_[ ] 使返回的间隔数值点配对
+ np.c_[ 数组1，数组2， … ]

In [1]:
import numpy as np

In [2]:
x,y = np.mgrid[1:3:1,2:4:0.5]
grid = np.c_[x.ravel(), y.ravel()]

In [3]:
print(x)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]]


In [4]:
print(y)

[[2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5]]


In [5]:
print(grid)

[[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]]
