# 垂直叠加

+ np.vstack()
+ 将两个数组按垂直方向叠加
+ np.vstack(数组1,数组2)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [4]:
c = np.vstack((a, b))

In [5]:
print(c)

[[1 2 3]
 [4 5 6]]
