# 常用函数-最大最小值

强制tensor转换为该数据类型  
tf.cast (张量名，dtype=数据类型)   

计算张量维度上元素的最小值     
tf.reduce_min (张量名)  

计算张量维度上元素的最大值  
tf.reduce_max (张量名)  

In [1]:
import tensorflow as tf
import numpy as np

In [ ]:
x1 = tf.constant ([1., 2., 3.],
dtype=tf.float64)
print(x1)
x2 = tf.cast (x1, tf.int32)
print(x2)
print (tf.reduce_min(x2), 
tf.reduce_max(x2))



In [11]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [12]:
b = tf.convert_to_tensor(a, dtype=tf.int32)
b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [13]:
c = tf.cast(b, tf.int64)
c 

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 2, 3, 4], dtype=int64)>

In [14]:
d = tf.reduce_min(c)
d

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [15]:
e = tf.reduce_max(c)
e

<tf.Tensor: shape=(), dtype=int64, numpy=4>