# 常用函数-数学运算

对应元素的四则运算：tf.add，tf.subtract，tf.multiply，tf.divide   
平方、次方与开方： tf.square，tf.pow，tf.sqrt   
矩阵乘：tf.matmul

### 对应元素的四则运算   
实现两个张量的对应元素相加   
tf.add (张量1，张量2)   

实现两个张量的对应元素相减   
tf.subtract (张量1，张量2)   

实现两个张量的对应元素相乘   
tf.multiply (张量1，张量2)   

实现两个张量的对应元素相除   
tf.divide (张量1，张量2)   

<font color='red'>只有维度相同的张量才可以做四则运算</font>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
a = tf.random.normal([3,4], mean=0, stddev=1)
a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.49672619,  0.67930806, -0.9374743 ,  0.54306555],
       [ 1.3227557 ,  1.535396  ,  0.94169813,  0.45979905],
       [ 0.61253613,  3.338286  , -0.53719676, -2.1382554 ]],
      dtype=float32)>

In [4]:
b = tf.random.normal([3,4], mean=0, stddev=1)
b

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.1770464 , -0.68431616,  0.16671982, -0.32864258],
       [-0.07565787, -0.7293364 ,  0.16884239, -0.35791475],
       [ 0.55291706,  1.9940399 ,  0.01873435,  1.9448869 ]],
      dtype=float32)>

In [5]:
c = tf.add(a,b)
c

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-6.73772573e-01, -5.00810146e-03, -7.70754457e-01,
         2.14422971e-01],
       [ 1.24709785e+00,  8.06059599e-01,  1.11054051e+00,
         1.01884305e-01],
       [ 1.16545320e+00,  5.33232594e+00, -5.18462420e-01,
        -1.93368435e-01]], dtype=float32)>

In [6]:
d = tf.subtract(a,b)
d

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.3196798 ,  1.3636242 , -1.1041942 ,  0.87170815],
       [ 1.3984135 ,  2.2647324 ,  0.77285576,  0.8177138 ],
       [ 0.05961907,  1.344246  , -0.5559311 , -4.0831423 ]],
      dtype=float32)>

In [7]:
e = tf.multiply(a,b)
e

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.08794358, -0.46486148, -0.15629555, -0.17847446],
       [-0.10007688, -1.1198201 ,  0.15899856, -0.16456886],
       [ 0.33868167,  6.6566753 , -0.01006403, -4.1586647 ]],
      dtype=float32)>

In [8]:
f = tf.divide(a,b)
f

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[  2.805627 ,  -0.9926816,  -5.6230526,  -1.6524503],
       [-17.483385 ,  -2.105196 ,   5.5773797,  -1.2846608],
       [  1.1078265,   1.674132 , -28.67442  ,  -1.099424 ]],
      dtype=float32)>

In [9]:
j = tf.ones([1,3])
j

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

In [10]:
h = tf.fill([1,3],3.)
h

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3., 3., 3.]], dtype=float32)>

In [11]:
i = tf.add(j, h)
i

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 4., 4.]], dtype=float32)>

In [12]:
g = tf.subtract(h,j)
g

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[2., 2., 2.]], dtype=float32)>

In [13]:
q = tf.multiply(j, h)
q

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3., 3., 3.]], dtype=float32)>

In [14]:
p = tf.divide(h, j)
p

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3., 3., 3.]], dtype=float32)>