# 常用函数-平方次方开方

计算某个张量的平方   
tf.square (张量名)   

计算某个张量的n次方     
tf.pow (张量名，n次方数)   

计算某个张量的开方     
tf.sqrt (张量名）  

In [6]:
import tensorflow as tf
import numpy as np

In [9]:
a = tf.fill([1,3],3.)
a

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3., 3., 3.]], dtype=float32)>

In [10]:
b = tf.square(a)
b

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[9., 9., 9.]], dtype=float32)>

In [11]:
c = tf.pow(a,3)
c

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[27., 27., 27.]], dtype=float32)>

In [13]:
# 原a中补填充的3必须为3.而不是3
d = tf.sqrt(a)
d

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.7320508, 1.7320508, 1.7320508]], dtype=float32)>