# 预备知识-条件语句

条件语句真返回A，条件语句假返回B  

tf.where(条件语句，真返回A，假返回B)

In [12]:
import tensorflow as tf

In [13]:
a = tf.constant([1,2,3,1,1])
b = tf.constant([0,1,3,4,5])

In [14]:
print(a)
print(b)

tf.Tensor([1 2 3 1 1], shape=(5,), dtype=int32)
tf.Tensor([0 1 3 4 5], shape=(5,), dtype=int32)


若a>b，返回a对应位置的元素，否则返回b对应位置的元素

In [15]:
c = tf.where(tf.greater(a,b), a, b)

In [16]:
print(c)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
